version: '3.8'
services:
  card-trader-back:
    build:
      context: ./services/card-trader-back
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      MONGO_URI: mongodb://mongodb:27017/nest

  card-trader-front:
    build:
      context: ./services/card-trader-front
      dockerfile: Dockerfile
    ports:
      - '3001:3000'

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
